apiVersion: v1
kind: Pod
metadata:
  name: my-site1
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: /homework
    - name: nginxconf
      mountPath: "/etc/nginx/config"  
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command: 
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/init"
    securityContext: 
      privileged: true
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
  - name: nginxconf
    hostPath:
      path: "/home/conf/"
      type: Directory
