apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-site2
  namespace: homework
spec:
  selector:
    matchLabels:
      app: nginx
      version: v01
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
        version: v01
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: workdir
          mountPath: /homework
        - name: nginxconf
          mountPath: "/etc/nginx"
        readinessProbe:
          exec:
            command:
            - cat
            - /homework/index.html
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: install
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
        volumeMounts:
        - name: workdir
          mountPath: "/init"
        securityContext:
          privileged: true
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
      - name: nginxconf
        hostPath:
          path: "/home/conf/"
          type: Directory
